language: python
python:
  - '3.6'

before_script:
  - pip install -r purbeurre/requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - python3 purbeurre/manage.py test