# Generated by Django 3.0.1 on 2020-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('date', models.TextField(max_length=100)),
                ('brands', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=100)),
                ('stores', models.CharField(max_length=300)),
                ('ingredients', models.TextField()),
                ('image', models.URLField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
