# Generated by Django 3.0.1 on 2020-01-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='date',
            field=models.TextField(max_length=100),
        ),
    ]
