# Generated by Django 3.0.1 on 2020-01-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200107_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
