# Generated by Django 3.0.1 on 2020-01-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='categories',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
