# Generated by Django 3.0.1 on 2020-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200107_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='nutriscore',
            field=models.CharField(max_length=100),
        ),
    ]
